
export const GET_SAFE_GRADE = 'GET_SAFE_GRADE';
export const GET_VISITED_AREA = 'GET_VISITED_AREA';
export const GET_VISITED_IPS = 'GET_VISITED_IPS';
export const GET_WEBSITES = 'GET_WEBSITES';
export const GET_COMPANY_NAME = 'GET_COMPANY_NAME';
export const GET_ATTACK_TYPE = 'GET_ATTACK_TYPE';
export const GET_URL_FILE = 'GET_URL_FILE';
export const GET_VISITED_COUNTRY = 'GET_VISITED_COUNTRY';
export const GET_ALARM_LIST = 'GET_ALARM_LIST';
export const GET_TREND_LIST = 'GET_TREND_LIST';

