export const SET_CONTEXT_TITLE = 'SET_CONTEXT_TITLE';

export const DATA_CENTER_GET_DETAIL_DATA = 'DATA_CENTER_GET_DETAIL_DATA';


// 网络外部攻击
export const NET_ATTACK_OUTSIDE_MAP_DATA = 'NET_ATTACK_OUTSIDE_MAP_DATA';
export const NET_ATTACK_OUTSIDE_IP = 'NET_ATTACK_OUTSIDE_IP';
export const NET_ATTACK_OUTSIDE_THREAT = 'NET_ATTACK_OUTSIDE_THREAT';

// 网络攻击
export const NET_ATTACK_TYPE_LIST = 'NET_ATTACK_TYPE_LIST';

// 常量类型
export const EVENT_TYPE_LIST = 'EVENT_TYPE_LIST';
export const PRODUCT_TYPE_LIST = 'PRODUCT_TYPE_LIST';
export const EVENT_THREAT_LIST = 'EVENT_THREAT_LIST';
export const EVENT_GRADE_LIST = 'EVENT_GRADE_LIST';
export const EVENT_RISK_LIST = 'EVENT_RISK_LIST';
export const DEVICE_TYPE_LIST = 'DEVICE_TYPE_LIST';

// 对话框
export const SET_DIALOG = 'SET_DIALOG';
//新网络攻击的值
export const SET_ACTIVE_SCREEN = 'SET_ACTIVE_SCREEN'
export const SET_INFO_LIST = 'SET_INFO_LIST'
