// 常量类型
export const SET_PARAMS ='SET_PARAMS';
export const EVENT_TYPE_LIST = 'EVENT_TYPE_LIST';
export const PRODUCT_TYPE_LIST = 'PRODUCT_TYPE_LIST';
export const EVENT_THREAT_LIST = 'EVENT_THREAT_LIST';
export const EVENT_GRADE_LIST = 'EVENT_GRADE_LIST';
export const EVENT_RISK_LIST = 'EVENT_RISK_LIST';
export const DEVICE_TYPE_LIST = 'DEVICE_TYPE_LIST';

export const GET_ALARM_INFO = 'GET_ALARM_INFO';
export const SET_HIGH_ALARM = 'SET_HIGH_ALARM';
export const SET_MIDDLE_ALARM = 'SET_MIDDLE_ALARM';
export const SET_ATTACK_PIE = 'SET_ATTACK_PIE';
export const GET_LINE_BY_EVENT_TYPE = 'GET_LINE_BY_EVENT_TYPE';
export const SET_ATTACK_TREND = 'SET_ATTACK_TREND';
export const SET_THREATED_TREAD = 'SET_THREATED_TREAD';
export const GET_EVENT_SUB_TYPE = 'GET_EVENT_SUB_TYPE';
export const GET_ASSET_NAME = 'GET_ASSET_NAME';
export const GET_EVENT_SRC_IP = 'GET_EVENT_SRC_IP';
export const SET_EVENT_SRC_BAR = 'SET_EVENT_SRC_BAR';
export const GET_EVENT_DST_IP = 'GET_EVENT_DST_IP';
export const GET_BLOCK_INFO = 'GET_BLOCK_INFO';
export const SET_BLOCK_INFO = 'SET_BLOCK_INFO';

export const GET_GEO_COORD_MAP = 'GET_GEO_COORD_MAP';
export const ON_SMALL_MAP_CHANGE = 'ON_SMALL_MAP_CHANGE';

export const GET_ALL_DATA = 'GET_ALL_DATA';
